trigger:
    branches:
        include:
        - master/*
    paths:
        include:
        - azure-pipilines-tryout.yml
pool:
    vmImage: 'ubuntu-16.04'
  
container: ubuntu:16.04
  
steps:
- bash: echo "start of step"
- script: printenv